<?php

use Illuminate\Database\Seeder;
use App\Librerias\municipios;

class municipiosSeeder extends Seeder
{
    public function run()
    {
        $municipios = array(
            ['id_municipio' =>1	,'id_region' =>10, 'estado' => 'activo', 'descripcion' => 'DISTRITO NACIONAL'],
            ['id_municipio' =>2	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'SAN CRISTOBAL'],
            ['id_municipio' =>3	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'BANI'],
            ['id_municipio' =>4	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'BAYAGUANA'],
            ['id_municipio' =>5	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'YAMASA'],
            ['id_municipio' =>8	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'MONTE PLATA'],
            ['id_municipio' =>10	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'AZUA'],
            ['id_municipio' =>11	,'id_region' =>6, 'estado' => 'activo', 'descripcion' => 'LAS MATAS DE FARFAN'],
            ['id_municipio' =>12	,'id_region' =>6, 'estado' => 'activo', 'descripcion' => 'SAN JUAN DE LA MAGUANA'],
            ['id_municipio' =>13	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'SAN JOSE DE OCOA'],
            ['id_municipio' =>14	,'id_region' =>6, 'estado' => 'activo', 'descripcion' => 'EL CERCADO'],
            ['id_municipio' =>15	,'id_region' =>6, 'estado' => 'activo', 'descripcion' => 'BANICA'],
            ['id_municipio' =>16	,'id_region' =>6, 'estado' => 'activo', 'descripcion' => 'COMENDADOR'],
            ['id_municipio' =>17	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'PADRE LAS CASAS'],
            ['id_municipio' =>18	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'BARAHONA'],
            ['id_municipio' =>19	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'CABRAL'],
            ['id_municipio' =>20	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'DUVERGE'],
            ['id_municipio' =>21	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'ENRIQUILLO'],
            ['id_municipio' =>22	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'NEYBA'],
            ['id_municipio' =>23	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'SAN PEDRO DE MACORIS'],
            ['id_municipio' =>24	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'LOS LLANOS'],
            ['id_municipio' =>25	,'id_region' =>8, 'estado' => 'activo', 'descripcion' => 'EL SEIBO'],
            ['id_municipio' =>26	,'id_region' =>8, 'estado' => 'activo', 'descripcion' => 'LA ROMANA'],
            ['id_municipio' =>27	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'HATO MAYOR'],
            ['id_municipio' =>28	,'id_region' =>8, 'estado' => 'activo', 'descripcion' => 'HIGUEY'],
            ['id_municipio' =>29	,'id_region' =>8, 'estado' => 'activo', 'descripcion' => 'MICHES'],
            ['id_municipio' =>30	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'RAMON SANTANA'],
            ['id_municipio' =>31	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'SANTIAGO DE LOS CABALLEROS'],
            ['id_municipio' =>32	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'TAMBORIL'],
            ['id_municipio' =>33	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'ESPERANZA'],
            ['id_municipio' =>34	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'MAO'],
            ['id_municipio' =>35	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'JANICO'],
            ['id_municipio' =>36	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'SAN JOSE DE LAS MATAS'],
            ['id_municipio' =>37	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'PUERTO PLATA'],
            ['id_municipio' =>38	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'IMBERT'],
            ['id_municipio' =>39	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'ALTAMIRA'],
            ['id_municipio' =>40	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'LUPERON'],
            ['id_municipio' =>41	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'MONTECRISTI'],
            ['id_municipio' =>42	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'MONCION'],
            ['id_municipio' =>43	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'RESTAURACION'],
            ['id_municipio' =>44	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'DAJABON'],
            ['id_municipio' =>45	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'GUAYUBIN'],
            ['id_municipio' =>46	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'SAN IGNACIO DE SABANETA'],
            ['id_municipio' =>47	,'id_region' =>2, 'estado' => 'activo', 'descripcion' => 'LA VEGA'],
            ['id_municipio' =>48	,'id_region' =>2, 'estado' => 'activo', 'descripcion' => 'BONAO'],
            ['id_municipio' =>49	,'id_region' =>2, 'estado' => 'activo', 'descripcion' => 'COTUI'],
            ['id_municipio' =>50	,'id_region' =>2, 'estado' => 'activo', 'descripcion' => 'JARABACOA'],
            ['id_municipio' =>51	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'VILLA TAPIA'],
            ['id_municipio' =>52	,'id_region' =>2, 'estado' => 'activo', 'descripcion' => 'CEVICOS'],
            ['id_municipio' =>53	,'id_region' =>2, 'estado' => 'activo', 'descripcion' => 'CONSTANZA'],
            ['id_municipio' =>54	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'MOCA'],
            ['id_municipio' =>55	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'SALCEDO'],
            ['id_municipio' =>56	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'SAN FRANCISCO DE MACORIS'],
            ['id_municipio' =>57	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'PIMENTEL'],
            ['id_municipio' =>58	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'VILLA RIVA'],
            ['id_municipio' =>59	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'CASTILLO'],
            ['id_municipio' =>60	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'CABRERA'],
            ['id_municipio' =>61	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'GASPAR HERNANDEZ'],
            ['id_municipio' =>63	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'EUGENIO MARIA DE HOSTOS'],
            ['id_municipio' =>64	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'TENARES'],
            ['id_municipio' =>65	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'SAMANA'],
            ['id_municipio' =>66	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'SANCHEZ'],
            ['id_municipio' =>67	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'SABANA DE LA MAR'],
            ['id_municipio' =>68	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'VILLA ALTAGRACIA'],
            ['id_municipio' =>69	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'PEDERNALES'],
            ['id_municipio' =>70	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'LA DESCUBIERTA'],
            ['id_municipio' =>71	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'NAGUA'],
            ['id_municipio' =>72	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'VILLA VASQUEZ'],
            ['id_municipio' =>73	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'LOMA DE CABRERA'],
            ['id_municipio' =>74	,'id_region' =>6, 'estado' => 'activo', 'descripcion' => 'PEDRO SANTANA'],
            ['id_municipio' =>75	,'id_region' =>6, 'estado' => 'activo', 'descripcion' => 'HONDO VALLE'],
            ['id_municipio' =>76	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'TAMAYO'],
            ['id_municipio' =>77	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'JIMANI'],
            ['id_municipio' =>78	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'VILLA JARAGUA'],
            ['id_municipio' =>79	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'VICENTE NOBLE'],
            ['id_municipio' =>80	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'PARAISO'],
            ['id_municipio' =>81	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'RIO SAN JUAN'],
            ['id_municipio' =>82	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'YAGUATE'],
            ['id_municipio' =>83	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'SABANA GRANDE DE PALENQUE'],
            ['id_municipio' =>84	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'NIZAO'],
            ['id_municipio' =>85	,'id_region' =>8, 'estado' => 'activo', 'descripcion' => 'SAN RAFAEL DEL YUMA'],
            ['id_municipio' =>86	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'PEPILLO SALCEDO'],
            ['id_municipio' =>87	,'id_region' =>2, 'estado' => 'activo', 'descripcion' => 'FANTINO'],
            ['id_municipio' =>88	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'CAYETANO GERMOSEN'],
            ['id_municipio' =>90	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'SABANA GRANDE DE BOYA'],
            ['id_municipio' =>91	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'OVIEDO'],
            ['id_municipio' =>92	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'LAGUNA SALADA'],
            ['id_municipio' =>93	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'BAJOS DE HAINA'],
            ['id_municipio' =>94	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'VILLA GONZALEZ'],
            ['id_municipio' =>95	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'LICEY AL MEDIO'],
            ['id_municipio' =>96	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'VILLA BISONO -NAVARRETE-'],
            ['id_municipio' =>97	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'SOSUA'],
            ['id_municipio' =>99	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'POSTRER RIO'],
            ['id_municipio' =>100	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'EL VALLE'],
            ['id_municipio' =>101	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'CASTAÑUELAS'],
            ['id_municipio' =>102	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'LOS HIDALGOS'],
            ['id_municipio' =>103	,'id_region' =>8, 'estado' => 'activo', 'descripcion' => 'GUAYMATE'],
            ['id_municipio' =>104	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'CAMBITA GARABITOS'],
            ['id_municipio' =>105	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'GUAYABAL'],
            ['id_municipio' =>106	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'PERALTA'],
            ['id_municipio' =>107	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'SABANA YEGUA'],
            ['id_municipio' =>108	,'id_region' =>6, 'estado' => 'activo', 'descripcion' => 'VALLEJUELO'],
            ['id_municipio' =>109	,'id_region' =>6, 'estado' => 'activo', 'descripcion' => 'BOHECHIO'],
            ['id_municipio' =>110	,'id_region' =>6, 'estado' => 'activo', 'descripcion' => 'EL LLANO'],
            ['id_municipio' =>111	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'POLO'],
            ['id_municipio' =>112	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'LOS RIOS '],
            ['id_municipio' =>113	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'GALVAN'],
            ['id_municipio' =>114	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'MELLA'],
            ['id_municipio' =>115	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'PARTIDO'],
            ['id_municipio' =>116	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'VILLA LOS ALMACIGOS'],
            ['id_municipio' =>117	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'LAS MATAS DE SANTA CRUZ'],
            ['id_municipio' =>118	,'id_region' =>2, 'estado' => 'activo', 'descripcion' => 'MAIMON'],
            ['id_municipio' =>119	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'ARENOSO'],
            ['id_municipio' =>120	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'GUANANICO'],
            ['id_municipio' =>121	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'VILLA ISABELA'],
            ['id_municipio' =>122	,'id_region' =>2, 'estado' => 'activo', 'descripcion' => 'JIMA ABAJO'],
            ['id_municipio' =>123	,'id_region' =>2, 'estado' => 'activo', 'descripcion' => 'PIEDRA BLANCA'],
            ['id_municipio' =>125	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'LAS YAYAS DE VIAJAMA'],
            ['id_municipio' =>126	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'TABARA ARRIBA'],
            ['id_municipio' =>128	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'CRISTOBAL'],
            ['id_municipio' =>129	,'id_region' =>6, 'estado' => 'activo', 'descripcion' => 'JUAN DE HERRERA'],
            ['id_municipio' =>130	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'EL PEÑON'],
            ['id_municipio' =>131	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'FUNDACION'],
            ['id_municipio' =>132	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'ESTEBANIA'],
            ['id_municipio' =>133	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'JAMAO AL NORTE'],
            ['id_municipio' =>134	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'LAS TERRENAS'],
            ['id_municipio' =>135	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'LAS CHARCAS'],
            ['id_municipio' =>136	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'EL FACTOR'],
            ['id_municipio' =>137	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'LAS SALINAS'],
            ['id_municipio' =>138	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'CONSUELO'],
            ['id_municipio' =>139	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'LOS CACAOS'],
            ['id_municipio' =>140	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'SAN GREGORIO DE NIGUA'],
            ['id_municipio' =>143	,'id_region' =>3, 'estado' => 'activo', 'descripcion' => 'LAS GUARANAS'],
            ['id_municipio' =>144	,'id_region' =>6, 'estado' => 'activo', 'descripcion' => 'JUAN SANTIAGO '],
            ['id_municipio' =>146	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'QUISQUEYA'],
            ['id_municipio' =>148	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'SABANA IGLESIA'],
            ['id_municipio' =>149	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'SAN VICTOR'],
            ['id_municipio' =>150	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'SABANA LARGA'],
            ['id_municipio' =>151	,'id_region' =>4, 'estado' => 'activo', 'descripcion' => 'EL PINO'],
            ['id_municipio' =>152	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'RANCHO ARRIBA'],
            ['id_municipio' =>153	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'PERALVILLO'],
            ['id_municipio' =>154	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'PUEBLO VIEJO'],
            ['id_municipio' =>155	,'id_region' =>2, 'estado' => 'activo', 'descripcion' => 'VILLA LA MATA'],
            ['id_municipio' =>156	,'id_region' =>5, 'estado' => 'activo', 'descripcion' => 'MATANZAS'],
            ['id_municipio' =>160	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'LA CIENAGA'],
            ['id_municipio' =>161	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'BAITOA'],
            ['id_municipio' =>167	,'id_region' =>7, 'estado' => 'activo', 'descripcion' => 'JAQUIMEYES'],
            ['id_municipio' =>175	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'VILLA MONTELLANO'],
            ['id_municipio' =>223	,'id_region' =>10, 'estado' => 'activo', 'descripcion' => 'SANTO DOMINGO ESTE'],
            ['id_municipio' =>224	,'id_region' =>10, 'estado' => 'activo', 'descripcion' => 'SANTO DOMINGO OESTE'],
            ['id_municipio' =>225	,'id_region' =>10, 'estado' => 'activo', 'descripcion' => 'SANTO DOMINGO NORTE'],
            ['id_municipio' =>226	,'id_region' =>10, 'estado' => 'activo', 'descripcion' => 'BOCA CHICA'],
            ['id_municipio' =>227	,'id_region' =>10, 'estado' => 'activo', 'descripcion' => 'SAN ANTONIO DE GUERRA'],
            ['id_municipio' =>228	,'id_region' =>10, 'estado' => 'activo', 'descripcion' => 'PEDRO BRAND'],
            ['id_municipio' =>229	,'id_region' =>10, 'estado' => 'activo', 'descripcion' => 'LOS ALCARRIZOS'],
            ['id_municipio' =>295	,'id_region' =>8, 'estado' => 'activo', 'descripcion' => 'VILLA HERMOSA'],
            ['id_municipio' =>350	,'id_region' =>1, 'estado' => 'activo', 'descripcion' => 'PUÑAL'],
            ['id_municipio' =>364	,'id_region' =>9, 'estado' => 'activo', 'descripcion' => 'GUAYACANES']
        );

        foreach ($municipios as $key => $value) {
            municipios::create($value);
        }
    }
}
