<?php

use Illuminate\Database\Seeder;
use App\Librerias\municipios;

class municipiosSeeder extends Seeder
{
    public function run()
    {
        $municipios = array(            
            ['id_municipio' =>87	 ,'id_provincia' => 27	,'descripcion' => 'FANTINO', 'estado' => 'activo'],
            ['id_municipio' =>115	 ,'id_provincia' => 6	,'descripcion' => 'PARTIDO', 'estado' => 'activo'],
            ['id_municipio' =>137	 ,'id_provincia' => 5	,'descripcion' => 'LAS SALINAS', 'estado' => 'activo'],
            ['id_municipio' =>12	 ,'id_provincia' => 25	,'descripcion' => 'SAN JUAN DE LA MAGUANA', 'estado' => 'activo'],
            ['id_municipio' =>32	 ,'id_provincia' => 28	,'descripcion' => 'TAMBORIL', 'estado' => 'activo'],
            ['id_municipio' =>122	 ,'id_provincia' => 14	,'descripcion' => 'JIMA ABAJO', 'estado' => 'activo'],
            ['id_municipio' =>136	 ,'id_provincia' => 15	,'descripcion' => 'EL FACTOR', 'estado' => 'activo'],
            ['id_municipio' =>88	 ,'id_provincia' => 10	,'descripcion' => 'CAYETANO GERMOSEN', 'estado' => 'activo'],
            ['id_municipio' =>26	 ,'id_provincia' => 13	,'descripcion' => 'LA ROMANA', 'estado' => 'activo'],
            ['id_municipio' =>135	 ,'id_provincia' => 3	,'descripcion' => 'LAS CHARCAS', 'estado' => 'activo'],
            ['id_municipio' =>120	 ,'id_provincia' => 21	,'descripcion' => 'GUANANICO', 'estado' => 'activo'],
            ['id_municipio' =>131	 ,'id_provincia' => 5	,'descripcion' => 'FUNDACION', 'estado' => 'activo'],
            ['id_municipio' =>1	     ,'id_provincia' => 1	,'descripcion' => 'DISTRITO NACIONAL', 'estado' => 'activo'],
            ['id_municipio' =>129	 ,'id_provincia' => 25	,'descripcion' => 'JUAN DE HERRERA', 'estado' => 'activo'],
            ['id_municipio' =>55	 ,'id_provincia' => 22	,'descripcion' => 'SALCEDO', 'estado' => 'activo'],
            ['id_municipio' =>19	 ,'id_provincia' => 5	,'descripcion' => 'CABRAL', 'estado' => 'activo'],
            ['id_municipio' =>110	 ,'id_provincia' => 9	,'descripcion' => 'EL LLANO', 'estado' => 'activo'],
            ['id_municipio' =>4	     ,'id_provincia' => 18	,'descripcion' => 'BAYAGUANA', 'estado' => 'activo'],
            ['id_municipio' =>146	 ,'id_provincia' => 26	,'descripcion' => 'QUISQUEYA', 'estado' => 'activo'],
            ['id_municipio' =>223	 ,'id_provincia' => 32	,'descripcion' => 'SANTO DOMINGO ESTE', 'estado' => 'activo'],
            ['id_municipio' =>61	 ,'id_provincia' => 10	,'descripcion' => 'GASPAR HERNANDEZ', 'estado' => 'activo'],
            ['id_municipio' =>97	 ,'id_provincia' => 21	,'descripcion' => 'SOSUA', 'estado' => 'activo'],
            ['id_municipio' =>99	 ,'id_provincia' => 12	,'descripcion' => 'POSTRER RIO', 'estado' => 'activo'],
            ['id_municipio' =>17	 ,'id_provincia' => 3	,'descripcion' => 'PADRE LAS CASAS', 'estado' => 'activo'],
            ['id_municipio' =>29	 ,'id_provincia' => 8	,'descripcion' => 'MICHES', 'estado' => 'activo'],
            ['id_municipio' =>73	 ,'id_provincia' => 6	,'descripcion' => 'LOMA DE CABRERA', 'estado' => 'activo'],
            ['id_municipio' =>65	 ,'id_provincia' => 23	,'descripcion' => 'SAMANA', 'estado' => 'activo'],
            ['id_municipio' =>143	 ,'id_provincia' => 7	,'descripcion' => 'LAS GUARANAS', 'estado' => 'activo'],
            ['id_municipio' =>153	 ,'id_provincia' => 18	,'descripcion' => 'PERALVILLO', 'estado' => 'activo'],
            ['id_municipio' =>21	 ,'id_provincia' => 5	,'descripcion' => 'ENRIQUILLO', 'estado' => 'activo'],
            ['id_municipio' =>144	 ,'id_provincia' => 9	,'descripcion' => 'JUAN SANTIAGO ', 'estado' => 'activo'],
            ['id_municipio' =>39	 ,'id_provincia' => 21	,'descripcion' => 'ALTAMIRA', 'estado' => 'activo'],
            ['id_municipio' =>52	 ,'id_provincia' => 27	,'descripcion' => 'CEVICOS', 'estado' => 'activo'],
            ['id_municipio' =>100	 ,'id_provincia' => 11	,'descripcion' => 'EL VALLE', 'estado' => 'activo'],
            ['id_municipio' =>149	 ,'id_provincia' => 10	,'descripcion' => 'SAN VICTOR', 'estado' => 'activo'],
            ['id_municipio' =>91	 ,'id_provincia' => 19	,'descripcion' => 'OVIEDO', 'estado' => 'activo'],
            ['id_municipio' =>103	 ,'id_provincia' => 13	,'descripcion' => 'GUAYMATE', 'estado' => 'activo'],
            ['id_municipio' =>105	 ,'id_provincia' => 3	,'descripcion' => 'GUAYABAL', 'estado' => 'activo'],
            ['id_municipio' =>34	 ,'id_provincia' => 30	,'descripcion' => 'MAO', 'estado' => 'activo'],
            ['id_municipio' =>69	 ,'id_provincia' => 19	,'descripcion' => 'PEDERNALES', 'estado' => 'activo'],
            ['id_municipio' =>150	 ,'id_provincia' => 31	,'descripcion' => 'SABANA LARGA', 'estado' => 'activo'],
            ['id_municipio' =>133	 ,'id_provincia' => 10	,'descripcion' => 'JAMAO AL NORTE', 'estado' => 'activo'],
            ['id_municipio' =>35	 ,'id_provincia' => 28	,'descripcion' => 'JANICO', 'estado' => 'activo'],
            ['id_municipio' =>175	 ,'id_provincia' => 21	,'descripcion' => 'VILLA MONTELLANO', 'estado' => 'activo'],
            ['id_municipio' =>102	 ,'id_provincia' => 21	,'descripcion' => 'LOS HIDALGOS', 'estado' => 'activo'],
            ['id_municipio' =>148	 ,'id_provincia' => 28	,'descripcion' => 'SABANA IGLESIA', 'estado' => 'activo'],
            ['id_municipio' =>77	 ,'id_provincia' => 12	,'descripcion' => 'JIMANI', 'estado' => 'activo'],
            ['id_municipio' =>224	 ,'id_provincia' => 32	,'descripcion' => 'SANTO DOMINGO OESTE', 'estado' => 'activo'],
            ['id_municipio' =>57	 ,'id_provincia' => 7	,'descripcion' => 'PIMENTEL', 'estado' => 'activo'],
            ['id_municipio' =>227	 ,'id_provincia' => 32	,'descripcion' => 'SAN ANTONIO DE GUERRA', 'estado' => 'activo'],
            ['id_municipio' =>44	 ,'id_provincia' => 6	,'descripcion' => 'DAJABON', 'estado' => 'activo'],
            ['id_municipio' =>90	 ,'id_provincia' => 18	,'descripcion' => 'SABANA GRANDE DE BOYA', 'estado' => 'activo'],
            ['id_municipio' =>92	 ,'id_provincia' => 30	,'descripcion' => 'LAGUNA SALADA', 'estado' => 'activo'],
            ['id_municipio' =>64	 ,'id_provincia' => 22	,'descripcion' => 'TENARES', 'estado' => 'activo'],
            ['id_municipio' =>119	 ,'id_provincia' => 7	,'descripcion' => 'ARENOSO', 'estado' => 'activo'],
            ['id_municipio' =>8	     ,'id_provincia' => 18	,'descripcion' => 'MONTE PLATA', 'estado' => 'activo'],
            ['id_municipio' =>83	 ,'id_provincia' => 24	,'descripcion' => 'SABANA GRANDE DE PALENQUE', 'estado' => 'activo'],
            ['id_municipio' =>46	 ,'id_provincia' => 29	,'descripcion' => 'SAN IGNACIO DE SABANETA', 'estado' => 'activo'],
            ['id_municipio' =>10	 ,'id_provincia' => 3	,'descripcion' => 'AZUA', 'estado' => 'activo'],
            ['id_municipio' =>24	 ,'id_provincia' => 26	,'descripcion' => 'LOS LLANOS', 'estado' => 'activo'],
            ['id_municipio' =>54	 ,'id_provincia' => 10	,'descripcion' => 'MOCA', 'estado' => 'activo'],
            ['id_municipio' =>51	 ,'id_provincia' => 22	,'descripcion' => 'VILLA TAPIA', 'estado' => 'activo'],
            ['id_municipio' =>28	 ,'id_provincia' => 2	,'descripcion' => 'HIGUEY', 'estado' => 'activo'],
            ['id_municipio' =>156	 ,'id_provincia' => 20	,'descripcion' => 'MATANZAS', 'estado' => 'activo'],
            ['id_municipio' =>49	 ,'id_provincia' => 27	,'descripcion' => 'COTUI', 'estado' => 'activo'],
            ['id_municipio' =>58	 ,'id_provincia' => 7	,'descripcion' => 'VILLA RIVA', 'estado' => 'activo'],
            ['id_municipio' =>117	 ,'id_provincia' => 17	,'descripcion' => 'LAS MATAS DE SANTA CRUZ', 'estado' => 'activo'],
            ['id_municipio' =>31	 ,'id_provincia' => 28	,'descripcion' => 'SANTIAGO DE LOS CABALLEROS', 'estado' => 'activo'],
            ['id_municipio' =>70	 ,'id_provincia' => 12	,'descripcion' => 'LA DESCUBIERTA', 'estado' => 'activo'],
            ['id_municipio' =>78	 ,'id_provincia' => 4	,'descripcion' => 'VILLA JARAGUA', 'estado' => 'activo'],
            ['id_municipio' =>226	 ,'id_provincia' => 32	,'descripcion' => 'BOCA CHICA', 'estado' => 'activo'],
            ['id_municipio' =>82	 ,'id_provincia' => 24	,'descripcion' => 'YAGUATE', 'estado' => 'activo'],
            ['id_municipio' =>95	 ,'id_provincia' => 28	,'descripcion' => 'LICEY AL MEDIO', 'estado' => 'activo'],
            ['id_municipio' =>108	 ,'id_provincia' => 25	,'descripcion' => 'VALLEJUELO', 'estado' => 'activo'],
            ['id_municipio' =>5	     ,'id_provincia' => 18	,'descripcion' => 'YAMASA', 'estado' => 'activo'],
            ['id_municipio' =>138	 ,'id_provincia' => 26	,'descripcion' => 'CONSUELO', 'estado' => 'activo'],
            ['id_municipio' =>16	 ,'id_provincia' => 9	,'descripcion' => 'COMENDADOR', 'estado' => 'activo'],
            ['id_municipio' =>41	 ,'id_provincia' => 17	,'descripcion' => 'MONTECRISTI', 'estado' => 'activo'],
            ['id_municipio' =>25	 ,'id_provincia' => 8	,'descripcion' => 'EL SEIBO', 'estado' => 'activo'],
            ['id_municipio' =>14	 ,'id_provincia' => 25	,'descripcion' => 'EL CERCADO', 'estado' => 'activo'],
            ['id_municipio' =>96	 ,'id_provincia' => 28	,'descripcion' => 'VILLA BISONO -NAVARRETE-', 'estado' => 'activo'],
            ['id_municipio' =>15	 ,'id_provincia' => 9	,'descripcion' => 'BANICA', 'estado' => 'activo'],
            ['id_municipio' =>56	 ,'id_provincia' => 7	,'descripcion' => 'SAN FRANCISCO DE MACORIS', 'estado' => 'activo'],
            ['id_municipio' =>128	 ,'id_provincia' => 12	,'descripcion' => 'CRISTOBAL', 'estado' => 'activo'],
            ['id_municipio' =>13	 ,'id_provincia' => 31	,'descripcion' => 'SAN JOSE DE OCOA', 'estado' => 'activo'],
            ['id_municipio' =>167	 ,'id_provincia' => 5	,'descripcion' => 'JAQUIMEYES', 'estado' => 'activo'],
            ['id_municipio' =>76	 ,'id_provincia' => 4	,'descripcion' => 'TAMAYO', 'estado' => 'activo'],
            ['id_municipio' =>71	 ,'id_provincia' => 15	,'descripcion' => 'NAGUA', 'estado' => 'activo'],
            ['id_municipio' =>130	 ,'id_provincia' => 5	,'descripcion' => 'EL PEÑON', 'estado' => 'activo'],
            ['id_municipio' =>350	 ,'id_provincia' => 28	,'descripcion' => 'PUÑAL', 'estado' => 'activo'],
            ['id_municipio' =>93	 ,'id_provincia' => 24	,'descripcion' => 'BAJOS DE HAINA', 'estado' => 'activo'],
            ['id_municipio' =>30	 ,'id_provincia' => 26	,'descripcion' => 'RAMON SANTANA', 'estado' => 'activo'],
            ['id_municipio' =>134	 ,'id_provincia' => 23	,'descripcion' => 'LAS TERRENAS', 'estado' => 'activo'],
            ['id_municipio' =>48	 ,'id_provincia' => 16	,'descripcion' => 'BONAO', 'estado' => 'activo'],
            ['id_municipio' =>18	 ,'id_provincia' => 5	,'descripcion' => 'BARAHONA', 'estado' => 'activo'],
            ['id_municipio' =>116	 ,'id_provincia' => 29	,'descripcion' => 'VILLA LOS ALMACIGOS', 'estado' => 'activo'],
            ['id_municipio' =>151	 ,'id_provincia' => 6	,'descripcion' => 'EL PINO', 'estado' => 'activo'],
            ['id_municipio' =>37	 ,'id_provincia' => 21	,'descripcion' => 'PUERTO PLATA', 'estado' => 'activo'],
            ['id_municipio' =>3	     ,'id_provincia' => 20	,'descripcion' => 'BANI', 'estado' => 'activo'],
            ['id_municipio' =>67	 ,'id_provincia' => 11	,'descripcion' => 'SABANA DE LA MAR', 'estado' => 'activo'],
            ['id_municipio' =>111	 ,'id_provincia' => 5	,'descripcion' => 'POLO', 'estado' => 'activo'],
            ['id_municipio' =>53	 ,'id_provincia' => 14	,'descripcion' => 'CONSTANZA', 'estado' => 'activo'],
            ['id_municipio' =>104	 ,'id_provincia' => 24	,'descripcion' => 'CAMBITA GARABITOS', 'estado' => 'activo'],
            ['id_municipio' =>118	 ,'id_provincia' => 16	,'descripcion' => 'MAIMON', 'estado' => 'activo'],
            ['id_municipio' =>60	 ,'id_provincia' => 15	,'descripcion' => 'CABRERA', 'estado' => 'activo'],
            ['id_municipio' =>86	 ,'id_provincia' => 17	,'descripcion' => 'PEPILLO SALCEDO', 'estado' => 'activo'],
            ['id_municipio' =>43	 ,'id_provincia' => 6	,'descripcion' => 'RESTAURACION', 'estado' => 'activo'],
            ['id_municipio' =>85	 ,'id_provincia' => 2	,'descripcion' => 'SAN RAFAEL DEL YUMA', 'estado' => 'activo'],
            ['id_municipio' =>81	 ,'id_provincia' => 15	,'descripcion' => 'RIO SAN JUAN', 'estado' => 'activo'],
            ['id_municipio' =>126	 ,'id_provincia' => 3	,'descripcion' => 'TABARA ARRIBA', 'estado' => 'activo'],
            ['id_municipio' =>114	 ,'id_provincia' => 12	,'descripcion' => 'MELLA', 'estado' => 'activo'],
            ['id_municipio' =>161	 ,'id_provincia' => 28	,'descripcion' => 'BAITOA', 'estado' => 'activo'],
            ['id_municipio' =>75	 ,'id_provincia' => 9	,'descripcion' => 'HONDO VALLE', 'estado' => 'activo'],
            ['id_municipio' =>42	 ,'id_provincia' => 29	,'descripcion' => 'MONCION', 'estado' => 'activo'],
            ['id_municipio' =>121	 ,'id_provincia' => 21	,'descripcion' => 'VILLA ISABELA', 'estado' => 'activo'],
            ['id_municipio' =>125	 ,'id_provincia' => 3	,'descripcion' => 'LAS YAYAS DE VIAJAMA', 'estado' => 'activo'],
            ['id_municipio' =>154	 ,'id_provincia' => 3	,'descripcion' => 'PUEBLO VIEJO', 'estado' => 'activo'],
            ['id_municipio' =>101	 ,'id_provincia' => 17	,'descripcion' => 'CASTAÑUELAS', 'estado' => 'activo'],
            ['id_municipio' =>68	 ,'id_provincia' => 24	,'descripcion' => 'VILLA ALTAGRACIA', 'estado' => 'activo'],
            ['id_municipio' =>79	 ,'id_provincia' => 5	,'descripcion' => 'VICENTE NOBLE', 'estado' => 'activo'],
            ['id_municipio' =>106	 ,'id_provincia' => 3	,'descripcion' => 'PERALTA', 'estado' => 'activo'],
            ['id_municipio' =>94	 ,'id_provincia' => 28	,'descripcion' => 'VILLA GONZALEZ', 'estado' => 'activo'],
            ['id_municipio' =>225	 ,'id_provincia' => 32	,'descripcion' => 'SANTO DOMINGO NORTE', 'estado' => 'activo'],
            ['id_municipio' =>123	 ,'id_provincia' => 16	,'descripcion' => 'PIEDRA BLANCA', 'estado' => 'activo'],
            ['id_municipio' =>22	 ,'id_provincia' => 4	,'descripcion' => 'NEYBA', 'estado' => 'activo'],
            ['id_municipio' =>27	 ,'id_provincia' => 11	,'descripcion' => 'HATO MAYOR', 'estado' => 'activo'],
            ['id_municipio' =>295	 ,'id_provincia' => 13	,'descripcion' => 'VILLA HERMOSA', 'estado' => 'activo'],
            ['id_municipio' =>132	 ,'id_provincia' => 3	,'descripcion' => 'ESTEBANIA', 'estado' => 'activo'],
            ['id_municipio' =>228	 ,'id_provincia' => 32	,'descripcion' => 'PEDRO BRAND', 'estado' => 'activo'],
            ['id_municipio' =>72	 ,'id_provincia' => 17	,'descripcion' => 'VILLA VASQUEZ', 'estado' => 'activo'],
            ['id_municipio' =>40	 ,'id_provincia' => 21	,'descripcion' => 'LUPERON', 'estado' => 'activo'],
            ['id_municipio' =>11	 ,'id_provincia' => 25	,'descripcion' => 'LAS MATAS DE FARFAN', 'estado' => 'activo'],
            ['id_municipio' =>38	 ,'id_provincia' => 21	,'descripcion' => 'IMBERT', 'estado' => 'activo'],
            ['id_municipio' =>2	     ,'id_provincia' => 24	,'descripcion' => 'SAN CRISTOBAL', 'estado' => 'activo'],
            ['id_municipio' =>50	 ,'id_provincia' => 14	,'descripcion' => 'JARABACOA', 'estado' => 'activo'],
            ['id_municipio' =>36	 ,'id_provincia' => 28	,'descripcion' => 'SAN JOSE DE LAS MATAS', 'estado' => 'activo'],
            ['id_municipio' =>152	 ,'id_provincia' => 31	,'descripcion' => 'RANCHO ARRIBA', 'estado' => 'activo'],
            ['id_municipio' =>113	 ,'id_provincia' => 4	,'descripcion' => 'GALVAN', 'estado' => 'activo'],
            ['id_municipio' =>364	 ,'id_provincia' => 26	,'descripcion' => 'GUAYACANES', 'estado' => 'activo'],
            ['id_municipio' =>140	 ,'id_provincia' => 24	,'descripcion' => 'SAN GREGORIO DE NIGUA', 'estado' => 'activo'],
            ['id_municipio' =>33	 ,'id_provincia' => 30	,'descripcion' => 'ESPERANZA', 'estado' => 'activo'],
            ['id_municipio' =>107	 ,'id_provincia' => 3	,'descripcion' => 'SABANA YEGUA', 'estado' => 'activo'],
            ['id_municipio' =>139	 ,'id_provincia' => 24	,'descripcion' => 'LOS CACAOS', 'estado' => 'activo'],
            ['id_municipio' =>109	 ,'id_provincia' => 25	,'descripcion' => 'BOHECHIO', 'estado' => 'activo'],
            ['id_municipio' =>47	 ,'id_provincia' => 14	,'descripcion' => 'LA VEGA', 'estado' => 'activo'],
            ['id_municipio' =>155	 ,'id_provincia' => 27	,'descripcion' => 'VILLA LA MATA', 'estado' => 'activo'],
            ['id_municipio' =>80	 ,'id_provincia' => 5	,'descripcion' => 'PARAISO', 'estado' => 'activo'],
            ['id_municipio' =>59	 ,'id_provincia' => 7	,'descripcion' => 'CASTILLO', 'estado' => 'activo'],
            ['id_municipio' =>63	 ,'id_provincia' => 7	,'descripcion' => 'EUGENIO MARIA DE HOSTOS', 'estado' => 'activo'],
            ['id_municipio' =>229	 ,'id_provincia' => 32	,'descripcion' => 'LOS ALCARRIZOS', 'estado' => 'activo'],
            ['id_municipio' =>66	 ,'id_provincia' => 23	,'descripcion' => 'SANCHEZ', 'estado' => 'activo'],
            ['id_municipio' =>84	 ,'id_provincia' => 20	,'descripcion' => 'NIZAO', 'estado' => 'activo'],
            ['id_municipio' =>74	 ,'id_provincia' => 9	,'descripcion' => 'PEDRO SANTANA', 'estado' => 'activo'],
            ['id_municipio' =>160	 ,'id_provincia' => 5	,'descripcion' => 'LA CIENAGA', 'estado' => 'activo'],
            ['id_municipio' =>20	 ,'id_provincia' => 12	,'descripcion' => 'DUVERGE', 'estado' => 'activo'],
            ['id_municipio' =>23	 ,'id_provincia' => 26	,'descripcion' => 'SAN PEDRO DE MACORIS', 'estado' => 'activo'],
            ['id_municipio' =>45	 ,'id_provincia' => 17	,'descripcion' => 'GUAYUBIN', 'estado' => 'activo'],
            ['id_municipio' =>112	 ,'id_provincia' => 4	,'descripcion' => 'LOS RIOS ', 'estado' => 'activo']
        );

        foreach ($municipios as $key => $value) {
            municipios::create($value);
        }
    }
}
